from utils.grid import Grid
from utils.led import LST1_01G01_UV01_00, LST1_01F06_GRN1_00
from systematic_sampler import Sampler
from monte_carlo_sampler import MonteCarloSampler
from geometric_model import GeometricModel
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from ICIW_Plots import make_square_subplots, cm2inch
import os

plt.style.use("ICIWstyle")
plt.style.use("visualization/publication_style.mplstyle")

class Optimizer:
    """
    Provides methods for evaluating and optimizing LED array configurations based on irradiance metrics.

    This class is designed to facilitate the analysis and optimization of LED configurations for irradiation module optimization.
    It supports reading simulation results, calculating performance metrics, optimizing configurations according to a weighted objective,
    generating Pareto fronts, and visualizing results. The optimization is based on two main criteria: the mean irradiance relative to a specified bound,
    and the homogeneity of the irradiance distribution.

    :param irradiance_bound: Maximum allowed irradiance in W m⁻². Used as a threshold for evaluating configurations.
    :type irradiance_bound: float

    :ivar irradiance_bound: The irradiance threshold used for all metric calculations and optimization.
    :vartype irradiance_bound: float

    :raises ValueError: If ``irradiance_bound`` is not positive.

    .. note::
        - The class does not perform any simulation itself; it operates on precomputed simulation results.
        - Configurations exceeding the irradiance bound are excluded from optimization during metric calculations.
    """

    def __init__(self, irradiance_bound: float) -> None:
        """
        Initialize the optimizer with the irradiance bound.

        :param irradiance_bound: Maximum allowed irradiance in W m⁻². Must be positive.
        :type irradiance_bound: float

        :raises ValueError: If ``irradiance_bound`` is not positive.
        """
        if irradiance_bound <= 0:
            raise ValueError("irradiance_bound must be positive.")
        self.irradiance_bound = irradiance_bound

    def read_simulations(self, filename: str) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        """
        Load precomputed simulation results from a compressed NumPy (.npz) file.

        This method retrieves arrays containing LED configurations, corresponding heights, mean irradiance values, maximum irradiance values, and standard deviations of irradiance for each configuration. The file must have been generated by a compatible simulation pipeline and must contain the following arrays: ``'configs'``, ``'z'``, ``'means'``, ``'max'``, and ``'stds'``.

        :param filename: Path to the .npz file containing simulation results. The file must be readable and contain the expected arrays.
        :type filename: str

        :returns: A tuple containing five arrays:

            - *configs* (numpy.ndarray) — LED configurations (shape: (N, …), dtype: object or float).
            - *z* (numpy.ndarray) — Heights for each configuration (shape: (N,), dtype: float, units: cm).
            - *means* (numpy.ndarray) — Mean irradiance values (shape: (N,), dtype: float, units: W m⁻²).
            - *max* (numpy.ndarray) — Maximum irradiance values (shape: (N,), dtype: float, units: W m⁻²).
            - *stds* (numpy.ndarray) — Standard deviation of irradiance values (shape: (N,), dtype: float, units: W m⁻²).
        :rtype: tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]

        :raises FileNotFoundError: If the specified file does not exist.
        :raises KeyError: If any of the required arrays are missing from the file.

        .. note::
            - The simulation results must have been saved in a compatible format, typically using the ``save_results`` function from :mod:`geometric_model`.
            - All arrays must have the same length along the first dimension.
        """
        data = np.load(filename, allow_pickle=True)
        configs = data['configs']
        z = data['z']
        means = data['means']
        max = data['max']
        stds = data['stds']
        return configs, z, means, max, stds

    def calc_metrics(self, means: np.ndarray, max: np.ndarray, stds: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        r"""
        Compute homogeneity and mean-to-bound ratio metrics for a set of irradiance configurations.

        For each configuration, this method calculates:

        - Homogeneity, defined as :math:`H = 1 - \frac{\mathrm{std}}{\mathrm{mean}}`,
          which quantifies the uniformity of the irradiance distribution (values closer to 1 indicate higher homogeneity).
        - Ratio of mean irradiance to the irradiance bound, :math:`\frac{E_{\mathrm{mean}}}{E_{\mathrm{bound}}}`.

        If the maximum irradiance for a configuration exceeds the irradiance bound (as set in the Optimizer instance),
        both metrics are set to 0 for that configuration for penalization.

        :param means: Array of mean irradiance values for each configuration (shape: (N,), dtype: float, units: W m⁻²).
        :type means: numpy.ndarray
        :param max: Array of maximum irradiance values for each configuration (shape: (N,), dtype: float, units: W m⁻²).
        :type max: numpy.ndarray
        :param stds: Array of standard deviation of irradiance values for each configuration (shape: (N,), dtype: float, units: W m⁻²).
        :type stds: numpy.ndarray

        :returns: A tuple containing two arrays:

            - *ratio_to_bound* (numpy.ndarray) — Mean irradiance ratios to the bound for each configuration (shape: (N,), dtype: float).
            - *homogeneity* (numpy.ndarray) — Homogeneity indices for each configuration (shape: (N,), dtype: float).
        :rtype: tuple[numpy.ndarray, numpy.ndarray]

        :raises ValueError: If input arrays do not have the same shape.

        .. note::
            - The irradiance bound is taken from the Optimizer instance (``self.irradiance_bound``).
            - No NaN or inf checking is performed on the input arrays.

        .. rubric:: Example

        .. code-block:: python

            import numpy as np
            from optimizer import Optimizer

            opt = Optimizer(irradiance_bound=150.0)
            means = np.array([100.0, 130.0, 160.0])
            max_vals = np.array([140.0, 155.0, 200.0])
            stds = np.array([10.0, 15.0, 20.0])

            ratio_to_bound, homogeneity = opt.calc_metrics(means, max_vals, stds)
            # Configurations where max > 150 W m⁻² receive a score of 0.
        """

        if not (means.shape == max.shape == stds.shape):
            raise ValueError("Input arrays 'means', 'max', and 'stds' must have the same shape.")

        homogeneity = 1 - (stds / means)
        ratio_to_bound = means / self.irradiance_bound

        # Penalize configurations exceeding the irradiance bound
        homogeneity = np.where(max > self.irradiance_bound, 0, homogeneity)
        ratio_to_bound = np.where(max > self.irradiance_bound, 0, ratio_to_bound)

        return ratio_to_bound, homogeneity

    def objective_function(self, t: float, ratio_to_bound: np.ndarray, homogeneity: np.ndarray) -> np.ndarray:
        r"""
        Compute a weighted objective score for each configuration based on mean irradiance and homogeneity.

        The objective function is defined as:

            .. math::
                f(t) = t \cdot \frac{E_{\mathrm{mean}}}{E_{\mathrm{bound}}} + (1 - t) \cdot H

        where:
            - :math:`t` is a weighting factor between 0 and 1.
            - :math:`E_{\mathrm{mean}}` is the mean irradiance for a configuration.
            - :math:`E_{\mathrm{bound}}` is the irradiance bound.
            - :math:`H` is the homogeneity for a configuration.

        :param t: Weighting factor between 0 and 1 (dimensionless). Determines the trade-off between mean irradiance and homogeneity.
        :type t: float
        :param ratio_to_bound: Array of mean irradiance ratios to the bound for each configuration (shape: (N,), dtype: float).
        :type ratio_to_bound: numpy.ndarray
        :param homogeneity: Array of homogeneity values for each configuration (shape: (N,), dtype: float).
        :type homogeneity: numpy.ndarray

        :returns: Objective function values for each configuration (shape: (N,), dtype: float).
        :rtype: numpy.ndarray

        .. rubric:: Example

        .. code-block:: python

            import numpy as np
            from optimizer import Optimizer

            opt = Optimizer(irradiance_bound=150.0)
            means = np.array([100.0, 130.0])
            max_vals = np.array([140.0, 145.0])
            stds = np.array([10.0, 5.0])

            ratio_to_bound, homogeneity = opt.calc_metrics(means, max_vals, stds)

            # Equal weight between irradiance and homogeneity
            scores = opt.objective_function(t=0.5, ratio_to_bound=ratio_to_bound, homogeneity=homogeneity)
        """
        return t * ratio_to_bound + (1 - t) * homogeneity

    def optimize(self, configurations: np.ndarray, z: np.ndarray, means: np.ndarray, max: np.ndarray, stds: np.ndarray, t: float) -> tuple:
        """
        Identify the optimal LED configuration for a specified weighting factor `t` by maximizing the objective function.

        This method evaluates all provided configurations using the weighted objective function (see :meth:`objective_function`) and returns the configuration with the highest score.

        Parameters
        ----------
        configurations : numpy.ndarray
            Array of LED configurations (shape: (N, ...), dtype: object or int/float).
        z : numpy.ndarray
            Array of heights for each configuration (shape: (N,), dtype: float, units: cm).
        means : numpy.ndarray
            Array of mean irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        max : numpy.ndarray
            Array of maximum irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        stds : numpy.ndarray
            Array of standard deviation of irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        t : float
            Weighting factor between 0 and 1 (dimensionless).

        Returns
        -------
        tuple
            A tuple containing:
                - best_configuration (numpy.ndarray): Best LED configuration (shape: as in `configurations`).
                - best_z (float): Height of the best configuration (units: cm).
                - best_ratio (float): Mean irradiance ratio to the bound for the best configuration (dimensionless).
                - best_homogeneity (float): Homogeneity index for the best configuration (dimensionless).
                - best_score (float): Objective function value for the best configuration (dimensionless).

        Raises
        ------
        ValueError
            If input arrays do not have compatible shapes.

        Notes
        -----
        - The irradiance bound is taken from the Optimizer instance.
        - Penalizes configurations exceeding the irradiance bound.
        - Assumes all input arrays are aligned along the first dimension.
        """
        ratio_to_bound, homogeneity = self.calc_metrics(means, max, stds)
        scores = self.objective_function(t, ratio_to_bound, homogeneity)
        best_index = np.argmax(scores)
        return configurations[best_index], z[best_index], ratio_to_bound[best_index], homogeneity[best_index], scores[best_index]

    def create_pareto_front(self, configurations: np.ndarray, z: np.ndarray, means: np.ndarray, max: np.ndarray, stds: np.ndarray, t_values: np.ndarray) -> tuple:
        """
        Generate a Pareto front by optimizing the objective function over a range of weighting factors `t`.

        For each value of `t` in `t_values`, the method finds the configuration that maximizes the objective function and collects unique solutions to form the Pareto front. Duplicate configurations (with the same configuration and height) are excluded.

        Parameters
        ----------
        configurations : numpy.ndarray
            Array of LED configurations (shape: (N, ...), dtype: object or int/float).
        z : numpy.ndarray
            Array of heights for each configuration (shape: (N,), dtype: float, units: cm).
        means : numpy.ndarray
            Array of mean irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        max : numpy.ndarray
            Array of maximum irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        stds : numpy.ndarray
            Array of standard deviation of irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        t_values : numpy.ndarray
            Array of weighting factors to optimize for (shape: (M,), dtype: float, values in [0, 1]).

        Returns
        -------
        tuple
            A tuple containing:
                - pareto_configs (list): List of Pareto optimal configurations (dtype: object or int/float).
                - pareto_z (list): List of heights for Pareto optimal configurations (dtype: float).
                - pareto_ratios (list): List of mean irradiance ratios for Pareto optimal configurations (dtype: float).
                - pareto_homogeneities (list): List of homogeneity indices for Pareto optimal configurations (dtype: float).
                - pareto_scores (list): List of scores for Pareto optimal configurations (dtype: float).

        Raises
        ------
        ValueError
            If input arrays do not have compatible shapes.

        Notes
        -----
        - The Pareto front is constructed by sweeping ``t`` from 0 to 1.
        - The returned lists are ordered by the order of `t_values`.
        """
        pareto_configs = []
        pareto_z = []
        pareto_ratios = []
        pareto_homogeneities = []
        pareto_scores = []

        for t in t_values:
            best_config, best_z, best_ratio, best_homogeneity, best_score = self.optimize(configurations, z, means, max, stds, t)
            # check if the configuration is already in the pareto front
            if (best_config in pareto_configs) and (best_z in pareto_z):
                continue
            pareto_configs.append(best_config)
            pareto_z.append(best_z)
            pareto_ratios.append(best_ratio)
            pareto_homogeneities.append(best_homogeneity)
            pareto_scores.append(best_score)

        return pareto_configs, pareto_z, pareto_ratios, pareto_homogeneities, pareto_scores
    
    def find_best_configuration(self, configurations: np.ndarray, z: np.ndarray, means: np.ndarray, max: np.ndarray, stds: np.ndarray) -> tuple:
        r"""
        Select the configuration that maximizes the product of mean irradiance ratio and homogeneity index.

        This method evaluates all configurations using the metric:

            .. math::
                    \text{score} = \frac{E_{\mathrm{mean}}}{E_{\mathrm{bound}}} \times H

        and returns the configuration with the highest score.

        Parameters
        ----------
        configurations : numpy.ndarray
            Array of LED configurations (shape: (N, ...), dtype: object or int/float).
        z : numpy.ndarray
            Array of heights for each configuration (shape: (N,), dtype: float, units: cm).
        means : numpy.ndarray
            Array of mean irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        max : numpy.ndarray
            Array of maximum irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).
        stds : numpy.ndarray
            Array of standard deviation of irradiance values for each configuration (shape: (N,), dtype: float, units: W/m²).

        Returns
        -------
        tuple
            A tuple containing:
                - best_configuration (numpy.ndarray): Best LED configuration (shape: as in `configurations`).
                - best_z (float): Height of the best configuration (units: cm).
                - best_ratio (float): Mean irradiance ratio to the bound for the best configuration (dimensionless).
                - best_homogeneity (float): Homogeneity index for the best configuration (dimensionless).
                - best_score (float): Product score for the best configuration (dimensionless).

        Raises
        ------
        ValueError
            If input arrays do not have compatible shapes.
        """
        ratio_to_bound, homogeneity = self.calc_metrics(means, max, stds)
        scores = ratio_to_bound * homogeneity
        best_index = np.argmax(scores)

        print("Best Configuration: ",  configurations[best_index])
        print("Max Irradiance: ", max[best_index])

        return configurations[best_index], z[best_index], ratio_to_bound[best_index], homogeneity[best_index], scores[best_index]
    
    def plot_pareto_front(
        self,
        ax: Axes,
        pareto_ratios: np.ndarray,
        pareto_homogeneities: np.ndarray,
        other_points: dict = {},
        title: str = ""
    ):
        r"""
        Visualizes the Pareto front for LED array optimization results, plotting mean irradiance ratio versus homogeneity.

        This method generates a scatter/line plot of Pareto optimal solutions, where each point represents a configuration's trade-off between mean irradiance (relative to a specified bound) and homogeneity of the irradiance distribution. Optionally, additional points (such as reference or benchmark solutions) can be overlaid for comparison.

        Parameters
        ----------
        ax : matplotlib.axes.Axes
            The matplotlib Axes object on which to draw the plot. Must be a valid Axes instance.
        pareto_ratios : numpy.ndarray
            1D array of mean irradiance ratios to the bound for Pareto optimal configurations. Each value should be a float in [0, 1] (dimensionless).
        pareto_homogeneities : numpy.ndarray
            1D array of homogeneity indices for Pareto optimal configurations. Each value should be a float in [0, 1] (dimensionless).
        other_points : dict, optional
            Dictionary of additional points to plot, where each key is a label (str) and each value is a tuple of the form (marker, ratio, homogeneity):

                - marker (str): Matplotlib marker style (e.g., 'x', '^', etc.).
                - ratio (float): Mean irradiance ratio to the bound (dimensionless).
                - homogeneity (float): Homogeneity index (dimensionless).

            Defaults to empty dict ({}), meaning no extra points are plotted.
        title : str, optional
            Title for the plot. Defaults to an empty string ("").

        Returns
        -------
        matplotlib.axes.Axes
            The Axes object with the Pareto front and any additional points plotted.
            
        Notes
        -----
        - The x-axis represents the mean irradiance ratio to the bound (unitless).
        - The y-axis represents the homogeneity index (unitless).
        - If ``other_points`` is not empty, each entry is plotted with its specified marker and label.
        - The function does not call ``plt.show()``; the user needs to call it after plotting to display the figure.
        """

        ax.plot(pareto_ratios, pareto_homogeneities, 'o:', label='Pareto Front')
        if other_points is not {}:
            # Use the color cycle, skipping the first color (used by Pareto front)
            m = plt.rcParams['axes.prop_cycle'].by_key()['color']
            m = m[1:]
            for i, (label, (marker, ratio, homogeneity)) in enumerate(other_points.items()):
                ax.scatter(ratio, homogeneity, label=label, s=64, color=m[i], marker=marker, zorder=5)

        ax.set_xlabel(r'$E_\mathrm{mean}\,/\,E_\mathrm{bound}$ / 1')
        ax.set_ylabel('Homogeneity / 1')
        ax.set_title(title, y=-0.28)

        return ax


def save_optimization_results(filename: str, pareto_configs, pareto_z, pareto_ratios, pareto_homogeneities, pareto_scores, best_config, best_z, best_ratio, best_homogeneity, best_score):
    """
    Serializes and saves the results of an LED array optimization process to a compressed NumPy ``.npz`` file.

    This function stores all relevant data from a multi-objective optimization, including the Pareto front and the best configuration found, into a single file for later retrieval and analysis. The saved file can be loaded using ``numpy.load`` or the corresponding ``read_optimization_results`` function.

    Parameters
    ----------
    filename : str
        Path (including filename) where the ``.npz`` file will be saved. Should end with ``.npz``.
    pareto_configs : list
        List of Pareto optimal LED configurations. Each entry should be a configuration array or object (dtype: object).
    pareto_z : list
        List of heights (float, units: cm) corresponding to each Pareto optimal configuration.
    pareto_ratios : list
        List of mean irradiance ratios to the bound for Pareto optimal configurations (float, dimensionless).
    pareto_homogeneities : list
        List of homogeneity indices for Pareto optimal configurations (float, dimensionless).
    pareto_scores : list
        List of objective function scores for Pareto optimal configurations (float, dimensionless).
    best_config : numpy.ndarray or object
        The best LED configuration found during optimization (array or object, dtype: object).
    best_z : float
        Height of the best configuration (units: cm).
    best_ratio : float
        Mean irradiance ratio to the bound for the best configuration (dimensionless).
    best_homogeneity : float
        Homogeneity index for the best configuration (dimensionless).
    best_score : float
        Objective function score for the best configuration (dimensionless).

    Returns
    -------
    None
        This function does not return a value. Results are written to disk.

    Raises
    ------
    OSError
        If the file cannot be written (e.g., due to permission issues or invalid path).

    Notes
    -----
    - All input lists/arrays must be serializable by NumPy. The function uses ``dtype=object`` for configurations to support arbitrary objects.
    - The file can be loaded using ``numpy.load(filename, allow_pickle=True)``.
    - No validation is performed on the physical correctness or consistency of the input data.
    """
    
    np.savez_compressed(
        filename,
        pareto_configs=np.array(pareto_configs, dtype=object),
        pareto_z=pareto_z,
        pareto_ratios=pareto_ratios,
        pareto_homogeneities=pareto_homogeneities,
        pareto_scores=pareto_scores,
        best_config=best_config,
        best_z=best_z,
        best_ratio=best_ratio,
        best_homogeneity=best_homogeneity,
        best_score=best_score
    )


def read_optimization_results(filename: str) -> tuple:
    """
    Load and return the results of an LED array optimization process from a compressed NumPy ``.npz`` file.

    This function retrieves all relevant data from a previously saved multi-objective optimization, including the Pareto front and the best configuration found. The file must have been created by a compatible saving function (such as ``save_optimization_results``) and must contain the expected arrays and objects.

    Parameters
    ----------
    filename : str
        Path to the ``.npz`` file containing the optimization results. The file must be readable and contain the expected arrays.

    Returns
    -------
    tuple
        A tuple containing the following elements, in order:

        - pareto_configs (numpy.ndarray): Array of Pareto optimal LED configurations (dtype: object).
        - pareto_z (numpy.ndarray): Array of heights for Pareto optimal configurations (float, units: cm).
        - pareto_ratios (numpy.ndarray): Array of mean irradiance ratios to the bound for Pareto optimal configurations (float, dimensionless).
        - pareto_homogeneities (numpy.ndarray): Array of homogeneity indices for Pareto optimal configurations (float, dimensionless).
        - pareto_scores (numpy.ndarray): Array of objective function scores for Pareto optimal configurations (float, dimensionless).
        - best_config (numpy.ndarray or object): Best LED configuration found during optimization (dtype: object).
        - best_z (float): Height of the best configuration (units: cm).
        - best_ratio (float): Mean irradiance ratio to the bound for the best configuration (dimensionless).
        - best_homogeneity (float): Homogeneity index for the best configuration (dimensionless).
        - best_score (float): Objective function score for the best configuration (dimensionless).

    Raises
    ------
    FileNotFoundError
        If the specified file does not exist.
    KeyError
        If any of the required arrays are missing from the file.

    Notes
    -----
    - The input file must be generated by a compatible saving function and must contain all required arrays.
    - All arrays are loaded with ``allow_pickle=True`` to support arbitrary objects in configurations.
    - No validation is performed on the physical correctness or consistency of the data.
    - The returned arrays are suitable for further analysis, visualization, or reporting.
    """
    data = np.load(filename, allow_pickle=True)
    pareto_configs = data['pareto_configs']
    pareto_z = data['pareto_z']
    pareto_ratios = data['pareto_ratios']
    pareto_homogeneities = data['pareto_homogeneities']
    pareto_scores = data['pareto_scores']
    best_config = data['best_config']
    best_z = data['best_z']
    best_ratio = data['best_ratio']
    best_homogeneity = data['best_homogeneity']
    best_score = data['best_score']
    return (pareto_configs, pareto_z, pareto_ratios, pareto_homogeneities, pareto_scores,
            best_config, best_z, best_ratio, best_homogeneity, best_score)


# Full example usage
if __name__ == "__main__":
    # Initialize the optimizer with an irradiance bound of 150.0 W/m²
    optimizer = Optimizer(irradiance_bound=150.0)
    
    # Load simulation results from file
    configs, z, means, max_vals, stds = optimizer.read_simulations('results\\examples\\example_MonteCarlo_simulation_results.npz')
    
    # Calculate metrics for all configurations
    ratio_to_bound, homogeneity = optimizer.calc_metrics(means, max_vals, stds)
    
    # Find the best configuration using product metric
    best_config, best_z, best_ratio, best_homogeneity, best_score = optimizer.find_best_configuration(
        configs, z, means, max_vals, stds)
    
    # Generate Pareto front by sweeping weighting factor t from 0 to 1
    t_values = np.linspace(0, 1, 21)
    pareto_configs, pareto_z, pareto_ratios, pareto_homogeneities, pareto_scores = optimizer.create_pareto_front(
        configs, z, means, max_vals, stds, t_values)
    
    # Visualize the Pareto front
    fig, ax = plt.subplots()
    optimizer.plot_pareto_front(
        ax,
        pareto_ratios,
        pareto_homogeneities,
        other_points={
            'Best Configuration': ('x', best_ratio, best_homogeneity),
        },
    )
    ax.legend()
    plt.tight_layout()
    plt.show()
    
    # Save optimization results to file
    save_optimization_results(
        filename="results\\examples\\example_optimization_results.npz",
        pareto_configs=pareto_configs,
        pareto_z=pareto_z,
        pareto_ratios=pareto_ratios,
        pareto_homogeneities=pareto_homogeneities,
        pareto_scores=pareto_scores,
        best_config=best_config,
        best_z=best_z,
        best_ratio=best_ratio,
        best_homogeneity=best_homogeneity,
        best_score=best_score
    )
    
    # Load optimization results from file
    results = read_optimization_results("results\\examples\\example_optimization_results.npz")






