import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
import matplotlib.colors as mcolors

def process_raytracing_file(filename : str, path : str) -> pd.DataFrame:
    """
    Parse a Speos raytracing output text file and return a DataFrame containing spatial coordinates and irradiance values.

    This function reads a whitespace-delimited text file generated by Speos raytracing simulations, extracts the spatial coordinates (x, y, z in mm), and the irradiance (in W/m^2), converts coordinates to centimeters, and returns a DataFrame with a uniform grid suitable for further analysis or visualization. Only the columns corresponding to the two varying spatial dimensions and the irradiance are retained in the output.

    :param filename: Name of the Speos output text file to read.
    :type filename: str
    :param path: Path to the directory containing the text file.
    :type path: str or pathlib.Path

    :returns: DataFrame with columns ["x", "y", "Irradiance"], where x and y are in centimeters and Irradiance is in W/m^2.
    :rtype: pandas.DataFrame

    :raises FileNotFoundError: If the specified file does not exist.
    :raises ValueError: If the file format is not as expected or columns are missing.

    .. note::
        - Assumes the input file has a header row and columns in the order: x, y, z, Irradiance, Reflection (Radiometric), Transmission (Radiometric), Absorption (Radiometric).
        - Only two spatial dimensions are retained (the two that vary in the dataset).
        - Coordinates are converted from millimeters to centimeters.

    **Example usage:**

    .. code-block:: python

        df = process_raytracing_file('output.txt', '/path/to/data')
        print(df.head())

    """

    data = np.loadtxt(Path(path) / filename, skiprows=1)
    data = pd.DataFrame(data, columns=["x", "y", "z", "Irradiance", "Reflection (Radiometric)", "Transmission (Radiometric)", "Absorption (Radiometric)"])

    # convert mm to cm
    data[["x", "y", "z"]] = data[["x", "y", "z"]] / 10.0
    # only return x,y,z, and irradiance columns
    data = data[["x", "y", "z", "Irradiance"]]

    # check which of data["x"] and data["y"] and data["z"] are not unique
    plot_variable_columns = []
    if data["x"].nunique() > 1:
        plot_variable_columns.append("x")
    if data["y"].nunique() > 1:
        plot_variable_columns.append("y")
    if data["z"].nunique() > 1:
        plot_variable_columns.append("z")

    # create uniform grid by pivoting the data
    data = data.pivot_table(index=plot_variable_columns[0], columns=plot_variable_columns[1], values='Irradiance').reset_index()
    data.columns.name = None  # remove the columns name
    data = data.melt(id_vars=plot_variable_columns[0], var_name=plot_variable_columns[1], value_name='Irradiance')
    data = data.sort_values(by=[plot_variable_columns[1], plot_variable_columns[0]]).reset_index(drop=True)

    # rename columns to x, y, irradiance
    data.columns = ["x", "y", "Irradiance"]
    return data


def calc_metrics(irr: pd.Series):
    r"""
    Compute the mean irradiance and homogeneity index from a series of irradiance values.

    The homogeneity index is defined as :math:`1 - \frac{\sigma}{\mu}` where :math:`\sigma` is the standard deviation and :math:`\mu` is the mean of the irradiance values. This provides a measure of uniformity, with 1 indicating perfect homogeneity.

    :param irr: Irradiance values to analyze.
    :type irr: pandas.Series or numpy.ndarray

    :returns: Tuple containing:
        - mean_irradiance (float): Mean of the irradiance values (W/m^2).
        - homogeneity (float): Homogeneity index (dimensionless, 0 to 1).
    :rtype: tuple

    :raises ValueError: If the input series is empty.

    .. note::
        - If the mean irradiance is zero, the homogeneity index is set to 0 to avoid division by zero.

    **Example usage:**

    .. code-block:: python

        mean, homo = calc_metrics(df['Irradiance'])
        print(f"Mean: {mean}, Homogeneity: {homo}")

    """
    mean_irradiance = np.mean(irr)
    homogeneity= 1 - np.std(irr)/mean_irradiance if mean_irradiance else 0

    return mean_irradiance, homogeneity


def plot_irradiance_raytracing(ax: Axes, data : pd.DataFrame, title: str = "", y_title: float = -0.5, v_max: float = -1., extent: tuple = (-2, -1, -2, -1), shrink_cbar: float = 1.0) -> Axes:
    """
    Visualize the irradiance distribution from raytracing data on a 2D grid using matplotlib.

    This function creates a color map of irradiance values on a spatial grid, with options for customizing the color scale, axis labels, and colorbar. The input DataFrame must contain columns 'x', 'y', and 'Irradiance', where x and y are in centimeters and Irradiance is in W/m^2.

    :param ax: Matplotlib Axes object to plot on. Must be created beforehand.
    :type ax: matplotlib.axes.Axes
    :param data: DataFrame containing columns 'x', 'y', and 'Irradiance'.
    :type data: pandas.DataFrame
    :param title: Title of the plot. Default is empty string.
    :type title: str, optional
    :param y_title: Vertical position of the title. Default is -0.5.
    :type y_title: float, optional
    :param v_max: Maximum value for the color scale. If -1, auto-scales to the next multiple of 5 above the max irradiance. Default is -1.
    :type v_max: float, optional
    :param extent: Tuple specifying (xmin, xmax, ymin, ymax) for the plot. If default, computed from data. Units: cm. Default is (-2, -1, -2, -1).
    :type extent: tuple, optional
    :param shrink_cbar: Factor to shrink the color bar. Default is 1.0.
    :type shrink_cbar: float, optional

    :returns: The matplotlib Axes object with the irradiance plot.
    :rtype: matplotlib.axes.Axes

    :raises ValueError: If required columns are missing from the DataFrame.

    .. note::
        - The function pivots the data to a 2D grid for plotting.
        - The color scale is normalized from 0 to v_max.
        - The function does not create a new figure; the user must supply an Axes object.

    **Example usage:**

    .. code-block:: python

        fig, ax = plt.subplots()
        plot_irradiance_raytracing(ax, df, title="Irradiance Map")
        plt.show()

    """

    # set color bar limits
    if v_max != -1.:
        vmax = v_max
    else:
        # set vmax to the next multiple of 5 above the max irradiance for better color scaling
        vmax = (int(data["Irradiance"].max() // 5) + 1) * 5
    # Set normalization so colorbar starts at 0 and ends at vmax
    norm = mcolors.Normalize(vmin=0, vmax=vmax, clip=False)

    # define contour levels based on vmax
    if vmax <= 30:
        step = 5
    if vmax <= 50:
        step = 10
    elif vmax <= 100:
        step = 20
    # elif vmax <= 150:
    #     step = 50  
    else:
        step = 50 
    levels = np.arange(0, vmax + step, step)

    # Pivot the data to create a 2D grid for imshow
    grid = data.pivot(index="y", columns="x", values="Irradiance")
    x = grid.columns.values
    y = grid.index.values
    irr = grid.values

    # set extent if not provided
    if extent == (-2, -1, -2, -1):
        extent = (x.min(), x.max(), y.min(), y.max())
    # Show the irradiance map using imshow
    im = ax.imshow(
        irr,
        origin='lower',
        extent=extent,
        aspect='equal',
        norm=norm,
        cmap='viridis'
    )

    cbar = ax.figure.colorbar(im, ax=ax, ticks=levels, shrink=shrink_cbar)
    cbar.set_label('$E$ / W m$^{-2}$')

    ax.set_xlabel('$X$ / cm')
    ax.set_ylabel('$Y$ / cm')
    ax.set_aspect('equal', 'box')

    # set x and y limits
    ax.set_xlim(extent[0], extent[1])
    ax.set_ylim(extent[2], extent[3])

    # set subtitle
    if title:
        ax.set_title(title, y=y_title, fontsize=10)

    return ax